import { Sparkles, Award } from "lucide-react";

export default function ScoreBreakdownPanel({ subScores = { budget: 35, goals: 35 }, improvements = [] }) {
  const budget = subScores?.budget ?? 35;
  const goals = subScores?.goals ?? 35;

  return (
    <div className="w-full mt-4 space-y-4 pt-4 border-t border-border/60">
      {/* Sub-scores (Budget Adherence + Goal Alignment out of 50 each) */}
      <div className="space-y-3">
        <h4 className="text-xs font-semibold text-textPrimary flex items-center gap-1.5 uppercase tracking-wider">
          <Award size={14} className="text-primary" /> Health Score Breakdown
        </h4>

        {/* Budget Adherence */}
        <div className="space-y-1">
          <div className="flex justify-between text-[11px]">
            <span className="text-textSecondary">Budget Adherence</span>
            <span className="font-semibold text-textPrimary">{budget} / 50 pts</span>
          </div>
          <div className="w-full h-1.5 bg-surface rounded-full overflow-hidden border border-border/40">
            <div 
              className="h-full bg-primary transition-all duration-500" 
              style={{ width: `${(budget / 50) * 100}%` }}
            />
          </div>
        </div>

        {/* Goal Alignment */}
        <div className="space-y-1">
          <div className="flex justify-between text-[11px]">
            <span className="text-textSecondary">Goal Alignment</span>
            <span className="font-semibold text-textPrimary">{goals} / 50 pts</span>
          </div>
          <div className="w-full h-1.5 bg-surface rounded-full overflow-hidden border border-border/40">
            <div 
              className="h-full bg-accent transition-all duration-500" 
              style={{ width: `${(goals / 50) * 100}%` }}
            />
          </div>
        </div>
      </div>

      {/* Improvements list generated by Grok AI */}
      {improvements && improvements.length > 0 && (
        <div className="space-y-2 pt-2 border-t border-border/40">
          <h4 className="text-xs font-semibold text-textPrimary flex items-center gap-1.5 uppercase tracking-wider">
            <Sparkles size={14} className="text-accent animate-pulse" /> Grok AI Score Tips
          </h4>
          <div className="space-y-2">
            {improvements.map((imp, idx) => (
              <div 
                key={idx} 
                className="p-2.5 rounded-xl bg-surface/40 border border-border/50 flex items-start gap-2.5 text-xs hover:border-accent/35 transition-all"
              >
                <div className="space-y-0.5">
                  <p className="font-medium text-textPrimary">{imp.action}</p>
                  <p className="text-[10px] text-textSecondary">{imp.why}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
